production:
  vkontakte_app_id: <%= ENV['VKONTAKTE_APP_ID'] %>
  vkontakte_app_secret: <%= ENV['VKONTAKTE_APP_SECRET'] %>
  vkontakte_app_token: <%= ENV['VKONTAKTE_APP_TOKEN'] %>

  twitter_app_id: <%= ENV['TWITTER_APP_ID'] %>
  twitter_app_secret: <%= ENV['TWITTER_APP_SECRET'] %>
